apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: k8s-multi-com-tls
spec:
  secretName: k8s-multi-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: bbbls.app
  dnsNames:
    - bbbls.app
    - www.bbbls.app
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - bbbls.app
          - www.bbbls.app
